[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
todo_app = "HftbTaZFBTHF4jYULWemURZpMctCXApuhZydQteB65RM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/create-profile.ts"
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/create-todo.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/toggle-and-close-todo.ts"
